# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/emuno018/Rshell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/emuno018/Rshell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/emuno018/Rshell/CMakeFiles /home/csmajs/emuno018/Rshell/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/emuno018/Rshell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rshell

# Build rule for target.
rshell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rshell
.PHONY : rshell

# fast build rule for target.
rshell/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/build
.PHONY : rshell/fast

#=============================================================================
# Target rules for targets named cmdExe_unitTest

# Build rule for target.
cmdExe_unitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmdExe_unitTest
.PHONY : cmdExe_unitTest

# fast build rule for target.
cmdExe_unitTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/build
.PHONY : cmdExe_unitTest/fast

#=============================================================================
# Target rules for targets named tstCmdExec_unitTest

# Build rule for target.
tstCmdExec_unitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tstCmdExec_unitTest
.PHONY : tstCmdExec_unitTest

# fast build rule for target.
tstCmdExec_unitTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/build
.PHONY : tstCmdExec_unitTest/fast

#=============================================================================
# Target rules for targets named redirecting_unitTest

# Build rule for target.
redirecting_unitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redirecting_unitTest
.PHONY : redirecting_unitTest

# fast build rule for target.
redirecting_unitTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/build
.PHONY : redirecting_unitTest/fast

#=============================================================================
# Target rules for targets named connector_unitTest

# Build rule for target.
connector_unitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 connector_unitTest
.PHONY : connector_unitTest

# fast build rule for target.
connector_unitTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/build
.PHONY : connector_unitTest/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/gtest/CMakeFiles/gtest.dir/build.make googletest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/Command.o: src/Command.cpp.o

.PHONY : src/Command.o

# target to build an object file
src/Command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Command.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/src/Command.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/Command.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Command.cpp.o
.PHONY : src/Command.cpp.o

src/Command.i: src/Command.cpp.i

.PHONY : src/Command.i

# target to preprocess a source file
src/Command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Command.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/src/Command.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/Command.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Command.cpp.i
.PHONY : src/Command.cpp.i

src/Command.s: src/Command.cpp.s

.PHONY : src/Command.s

# target to generate assembly for a file
src/Command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Command.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/src/Command.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/Command.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Command.cpp.s
.PHONY : src/Command.cpp.s

src/CommandLine.o: src/CommandLine.cpp.o

.PHONY : src/CommandLine.o

# target to build an object file
src/CommandLine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/CommandLine.cpp.o
.PHONY : src/CommandLine.cpp.o

src/CommandLine.i: src/CommandLine.cpp.i

.PHONY : src/CommandLine.i

# target to preprocess a source file
src/CommandLine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/CommandLine.cpp.i
.PHONY : src/CommandLine.cpp.i

src/CommandLine.s: src/CommandLine.cpp.s

.PHONY : src/CommandLine.s

# target to generate assembly for a file
src/CommandLine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/CommandLine.cpp.s
.PHONY : src/CommandLine.cpp.s

src/DoubleAmpersand.o: src/DoubleAmpersand.cpp.o

.PHONY : src/DoubleAmpersand.o

# target to build an object file
src/DoubleAmpersand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/DoubleAmpersand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/DoubleAmpersand.cpp.o
.PHONY : src/DoubleAmpersand.cpp.o

src/DoubleAmpersand.i: src/DoubleAmpersand.cpp.i

.PHONY : src/DoubleAmpersand.i

# target to preprocess a source file
src/DoubleAmpersand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/DoubleAmpersand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/DoubleAmpersand.cpp.i
.PHONY : src/DoubleAmpersand.cpp.i

src/DoubleAmpersand.s: src/DoubleAmpersand.cpp.s

.PHONY : src/DoubleAmpersand.s

# target to generate assembly for a file
src/DoubleAmpersand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/DoubleAmpersand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/DoubleAmpersand.cpp.s
.PHONY : src/DoubleAmpersand.cpp.s

src/InputRedirector.o: src/InputRedirector.cpp.o

.PHONY : src/InputRedirector.o

# target to build an object file
src/InputRedirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/InputRedirector.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/InputRedirector.cpp.o
.PHONY : src/InputRedirector.cpp.o

src/InputRedirector.i: src/InputRedirector.cpp.i

.PHONY : src/InputRedirector.i

# target to preprocess a source file
src/InputRedirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/InputRedirector.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/InputRedirector.cpp.i
.PHONY : src/InputRedirector.cpp.i

src/InputRedirector.s: src/InputRedirector.cpp.s

.PHONY : src/InputRedirector.s

# target to generate assembly for a file
src/InputRedirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/InputRedirector.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/InputRedirector.cpp.s
.PHONY : src/InputRedirector.cpp.s

src/Or.o: src/Or.cpp.o

.PHONY : src/Or.o

# target to build an object file
src/Or.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Or.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Or.cpp.o
.PHONY : src/Or.cpp.o

src/Or.i: src/Or.cpp.i

.PHONY : src/Or.i

# target to preprocess a source file
src/Or.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Or.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Or.cpp.i
.PHONY : src/Or.cpp.i

src/Or.s: src/Or.cpp.s

.PHONY : src/Or.s

# target to generate assembly for a file
src/Or.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Or.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Or.cpp.s
.PHONY : src/Or.cpp.s

src/OutputAppender.o: src/OutputAppender.cpp.o

.PHONY : src/OutputAppender.o

# target to build an object file
src/OutputAppender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/OutputAppender.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/OutputAppender.cpp.o
.PHONY : src/OutputAppender.cpp.o

src/OutputAppender.i: src/OutputAppender.cpp.i

.PHONY : src/OutputAppender.i

# target to preprocess a source file
src/OutputAppender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/OutputAppender.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/OutputAppender.cpp.i
.PHONY : src/OutputAppender.cpp.i

src/OutputAppender.s: src/OutputAppender.cpp.s

.PHONY : src/OutputAppender.s

# target to generate assembly for a file
src/OutputAppender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/OutputAppender.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/OutputAppender.cpp.s
.PHONY : src/OutputAppender.cpp.s

src/OutputRedirector.o: src/OutputRedirector.cpp.o

.PHONY : src/OutputRedirector.o

# target to build an object file
src/OutputRedirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/OutputRedirector.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/OutputRedirector.cpp.o
.PHONY : src/OutputRedirector.cpp.o

src/OutputRedirector.i: src/OutputRedirector.cpp.i

.PHONY : src/OutputRedirector.i

# target to preprocess a source file
src/OutputRedirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/OutputRedirector.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/OutputRedirector.cpp.i
.PHONY : src/OutputRedirector.cpp.i

src/OutputRedirector.s: src/OutputRedirector.cpp.s

.PHONY : src/OutputRedirector.s

# target to generate assembly for a file
src/OutputRedirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/OutputRedirector.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/src/OutputRedirector.cpp.s
.PHONY : src/OutputRedirector.cpp.s

src/Pipe.o: src/Pipe.cpp.o

.PHONY : src/Pipe.o

# target to build an object file
src/Pipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Pipe.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Pipe.cpp.o
.PHONY : src/Pipe.cpp.o

src/Pipe.i: src/Pipe.cpp.i

.PHONY : src/Pipe.i

# target to preprocess a source file
src/Pipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Pipe.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Pipe.cpp.i
.PHONY : src/Pipe.cpp.i

src/Pipe.s: src/Pipe.cpp.s

.PHONY : src/Pipe.s

# target to generate assembly for a file
src/Pipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/Pipe.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/Pipe.cpp.s
.PHONY : src/Pipe.cpp.s

src/SemiColon.o: src/SemiColon.cpp.o

.PHONY : src/SemiColon.o

# target to build an object file
src/SemiColon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/SemiColon.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/SemiColon.cpp.o
.PHONY : src/SemiColon.cpp.o

src/SemiColon.i: src/SemiColon.cpp.i

.PHONY : src/SemiColon.i

# target to preprocess a source file
src/SemiColon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/SemiColon.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/SemiColon.cpp.i
.PHONY : src/SemiColon.cpp.i

src/SemiColon.s: src/SemiColon.cpp.s

.PHONY : src/SemiColon.s

# target to generate assembly for a file
src/SemiColon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/SemiColon.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/src/SemiColon.cpp.s
.PHONY : src/SemiColon.cpp.s

src/TestCommand.o: src/TestCommand.cpp.o

.PHONY : src/TestCommand.o

# target to build an object file
src/TestCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/TestCommand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/src/TestCommand.cpp.o
.PHONY : src/TestCommand.cpp.o

src/TestCommand.i: src/TestCommand.cpp.i

.PHONY : src/TestCommand.i

# target to preprocess a source file
src/TestCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/TestCommand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/src/TestCommand.cpp.i
.PHONY : src/TestCommand.cpp.i

src/TestCommand.s: src/TestCommand.cpp.s

.PHONY : src/TestCommand.s

# target to generate assembly for a file
src/TestCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/TestCommand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/src/TestCommand.cpp.s
.PHONY : src/TestCommand.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rshell.dir/build.make CMakeFiles/rshell.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

unit_tests/cmdExe_unitTest.o: unit_tests/cmdExe_unitTest.cpp.o

.PHONY : unit_tests/cmdExe_unitTest.o

# target to build an object file
unit_tests/cmdExe_unitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/unit_tests/cmdExe_unitTest.cpp.o
.PHONY : unit_tests/cmdExe_unitTest.cpp.o

unit_tests/cmdExe_unitTest.i: unit_tests/cmdExe_unitTest.cpp.i

.PHONY : unit_tests/cmdExe_unitTest.i

# target to preprocess a source file
unit_tests/cmdExe_unitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/unit_tests/cmdExe_unitTest.cpp.i
.PHONY : unit_tests/cmdExe_unitTest.cpp.i

unit_tests/cmdExe_unitTest.s: unit_tests/cmdExe_unitTest.cpp.s

.PHONY : unit_tests/cmdExe_unitTest.s

# target to generate assembly for a file
unit_tests/cmdExe_unitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmdExe_unitTest.dir/build.make CMakeFiles/cmdExe_unitTest.dir/unit_tests/cmdExe_unitTest.cpp.s
.PHONY : unit_tests/cmdExe_unitTest.cpp.s

unit_tests/connector_unitTest.o: unit_tests/connector_unitTest.cpp.o

.PHONY : unit_tests/connector_unitTest.o

# target to build an object file
unit_tests/connector_unitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/unit_tests/connector_unitTest.cpp.o
.PHONY : unit_tests/connector_unitTest.cpp.o

unit_tests/connector_unitTest.i: unit_tests/connector_unitTest.cpp.i

.PHONY : unit_tests/connector_unitTest.i

# target to preprocess a source file
unit_tests/connector_unitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/unit_tests/connector_unitTest.cpp.i
.PHONY : unit_tests/connector_unitTest.cpp.i

unit_tests/connector_unitTest.s: unit_tests/connector_unitTest.cpp.s

.PHONY : unit_tests/connector_unitTest.s

# target to generate assembly for a file
unit_tests/connector_unitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connector_unitTest.dir/build.make CMakeFiles/connector_unitTest.dir/unit_tests/connector_unitTest.cpp.s
.PHONY : unit_tests/connector_unitTest.cpp.s

unit_tests/redirecting_unitTest.o: unit_tests/redirecting_unitTest.cpp.o

.PHONY : unit_tests/redirecting_unitTest.o

# target to build an object file
unit_tests/redirecting_unitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/unit_tests/redirecting_unitTest.cpp.o
.PHONY : unit_tests/redirecting_unitTest.cpp.o

unit_tests/redirecting_unitTest.i: unit_tests/redirecting_unitTest.cpp.i

.PHONY : unit_tests/redirecting_unitTest.i

# target to preprocess a source file
unit_tests/redirecting_unitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/unit_tests/redirecting_unitTest.cpp.i
.PHONY : unit_tests/redirecting_unitTest.cpp.i

unit_tests/redirecting_unitTest.s: unit_tests/redirecting_unitTest.cpp.s

.PHONY : unit_tests/redirecting_unitTest.s

# target to generate assembly for a file
unit_tests/redirecting_unitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redirecting_unitTest.dir/build.make CMakeFiles/redirecting_unitTest.dir/unit_tests/redirecting_unitTest.cpp.s
.PHONY : unit_tests/redirecting_unitTest.cpp.s

unit_tests/tstCmdExec_unitTest.o: unit_tests/tstCmdExec_unitTest.cpp.o

.PHONY : unit_tests/tstCmdExec_unitTest.o

# target to build an object file
unit_tests/tstCmdExec_unitTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/unit_tests/tstCmdExec_unitTest.cpp.o
.PHONY : unit_tests/tstCmdExec_unitTest.cpp.o

unit_tests/tstCmdExec_unitTest.i: unit_tests/tstCmdExec_unitTest.cpp.i

.PHONY : unit_tests/tstCmdExec_unitTest.i

# target to preprocess a source file
unit_tests/tstCmdExec_unitTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/unit_tests/tstCmdExec_unitTest.cpp.i
.PHONY : unit_tests/tstCmdExec_unitTest.cpp.i

unit_tests/tstCmdExec_unitTest.s: unit_tests/tstCmdExec_unitTest.cpp.s

.PHONY : unit_tests/tstCmdExec_unitTest.s

# target to generate assembly for a file
unit_tests/tstCmdExec_unitTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tstCmdExec_unitTest.dir/build.make CMakeFiles/tstCmdExec_unitTest.dir/unit_tests/tstCmdExec_unitTest.cpp.s
.PHONY : unit_tests/tstCmdExec_unitTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cmdExe_unitTest"
	@echo "... connector_unitTest"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... redirecting_unitTest"
	@echo "... rshell"
	@echo "... tstCmdExec_unitTest"
	@echo "... src/Command.o"
	@echo "... src/Command.i"
	@echo "... src/Command.s"
	@echo "... src/CommandLine.o"
	@echo "... src/CommandLine.i"
	@echo "... src/CommandLine.s"
	@echo "... src/DoubleAmpersand.o"
	@echo "... src/DoubleAmpersand.i"
	@echo "... src/DoubleAmpersand.s"
	@echo "... src/InputRedirector.o"
	@echo "... src/InputRedirector.i"
	@echo "... src/InputRedirector.s"
	@echo "... src/Or.o"
	@echo "... src/Or.i"
	@echo "... src/Or.s"
	@echo "... src/OutputAppender.o"
	@echo "... src/OutputAppender.i"
	@echo "... src/OutputAppender.s"
	@echo "... src/OutputRedirector.o"
	@echo "... src/OutputRedirector.i"
	@echo "... src/OutputRedirector.s"
	@echo "... src/Pipe.o"
	@echo "... src/Pipe.i"
	@echo "... src/Pipe.s"
	@echo "... src/SemiColon.o"
	@echo "... src/SemiColon.i"
	@echo "... src/SemiColon.s"
	@echo "... src/TestCommand.o"
	@echo "... src/TestCommand.i"
	@echo "... src/TestCommand.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... unit_tests/cmdExe_unitTest.o"
	@echo "... unit_tests/cmdExe_unitTest.i"
	@echo "... unit_tests/cmdExe_unitTest.s"
	@echo "... unit_tests/connector_unitTest.o"
	@echo "... unit_tests/connector_unitTest.i"
	@echo "... unit_tests/connector_unitTest.s"
	@echo "... unit_tests/redirecting_unitTest.o"
	@echo "... unit_tests/redirecting_unitTest.i"
	@echo "... unit_tests/redirecting_unitTest.s"
	@echo "... unit_tests/tstCmdExec_unitTest.o"
	@echo "... unit_tests/tstCmdExec_unitTest.i"
	@echo "... unit_tests/tstCmdExec_unitTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

